In [2]:
import torch
import numpy as np

In [7]:
x = torch.empty(2,2,3,4)
print(x)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [10]:
x = torch.rand(2,2)
print(x)

tensor([[0.5339, 0.7085],
        [0.6734, 0.8166]])


In [11]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [16]:
x = torch.rand(2,2)
print(x)

tensor([[0.5579, 0.0284],
        [0.4253, 0.9449]])


In [15]:
x = torch.rand(2,2, dtype=torch.float16)
print(x.size)

<built-in method size of Tensor object at 0x000001948F430B80>


In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z = torch.add(x,y)
print(z)



tensor([[0.1064, 0.7807],
        [0.4271, 0.0406]])
tensor([[0.8257, 0.3910],
        [0.1929, 0.5880]])
tensor([[0.9321, 1.1717],
        [0.6200, 0.6286]])


In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.7805, 0.7341],
        [0.3171, 0.2675]])
tensor([[0.1126, 0.2725],
        [0.1338, 0.1936]])
tensor([[0.8932, 1.0065],
        [0.4510, 0.4610]])


In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x - y
z = torch.add(x,y)
print(z)


tensor([[0.5583, 0.2910],
        [0.9778, 0.1567]])
tensor([[0.3041, 0.2096],
        [0.8869, 0.2314]])
tensor([[0.8623, 0.5007],
        [1.8647, 0.3881]])


In [22]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z = torch.add(x,y)
print(z)
y.sub_(x)
print(y)


tensor([[0.6912, 0.8984],
        [0.5637, 0.7255]])
tensor([[0.2630, 0.1807],
        [0.0219, 0.9093]])
tensor([[0.9541, 1.0791],
        [0.5856, 1.6348]])
tensor([[-0.4282, -0.7177],
        [-0.5418,  0.1838]])


In [25]:
x = torch.rand(4,4)
print(x)
y = x.view(-1, 8)
print(y)

tensor([[0.3912, 0.7176, 0.1050, 0.9727],
        [0.7474, 0.3447, 0.8855, 0.5140],
        [0.8829, 0.2607, 0.7030, 0.4802],
        [0.6932, 0.5412, 0.0382, 0.7102]])
tensor([[0.3912, 0.7176, 0.1050, 0.9727, 0.7474, 0.3447, 0.8855, 0.5140],
        [0.8829, 0.2607, 0.7030, 0.4802, 0.6932, 0.5412, 0.0382, 0.7102]])


In [28]:
a = torch.ones(5)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
