In [33]:
import torch
import numpy as np

In [34]:
x = torch.empty(2,2,3,4)
print(x)

tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 4.2246e-39, 1.8788e+31, 1.7220e+22],
          [2.1715e-18, 3.3560e-06, 6.5919e-10, 8.3566e+20]],

         [[1.7012e-04, 1.3592e+22, 2.1670e-04, 1.3226e-08],
          [3.2918e-09, 2.5957e-09, 1.2698e+19, 2.3881e-18],
          [3.1360e+27, 7.0800e+31, 3.1095e-18, 4.7851e+22]]],


        [[[2.8826e+32, 4.4248e+30, 7.6729e+34, 2.1707e-18],
          [4.5447e+30, 7.0062e+22, 2.1715e-18, 4.5447e+30],
          [7.0062e+22, 2.1707e-18, 1.9284e+31, 3.2314e-18]],

         [[7.4767e+20, 8.4108e+20, 1.0016e-11, 1.6691e+22],
          [1.3665e+22, 2.1765e-04, 1.7680e-04, 2.6582e-06],
          [5.2354e+22, 2.1707e-18, 7.2128e+22, 2.1715e-18]]]])


In [35]:
x = torch.rand(2,2)
print(x)

tensor([[0.2774, 0.5655],
        [0.3174, 0.2655]])


In [36]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [37]:
x = torch.rand(2,2)
print(x)

tensor([[0.7853, 0.1370],
        [0.4995, 0.8529]])


In [38]:
x = torch.rand(2,2, dtype=torch.float16)
print(x.size)

<built-in method size of Tensor object at 0x000001948F560EF0>


In [39]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z = torch.add(x,y)
print(z)



tensor([[0.4180, 0.8362],
        [0.6983, 0.5961]])
tensor([[0.6281, 0.4404],
        [0.4508, 0.7065]])
tensor([[1.0461, 1.2766],
        [1.1492, 1.3026]])


In [40]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.1136, 0.8269],
        [0.7386, 0.2696]])
tensor([[0.2868, 0.8082],
        [0.4969, 0.7081]])
tensor([[0.4004, 1.6351],
        [1.2355, 0.9776]])


In [41]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x - y
z = torch.add(x,y)
print(z)


tensor([[0.3830, 0.8237],
        [0.2663, 0.2216]])
tensor([[0.8993, 0.0478],
        [0.8160, 0.7532]])
tensor([[1.2823, 0.8715],
        [1.0824, 0.9749]])


In [42]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x + y
z = torch.add(x,y)
print(z)
y.sub_(x)
print(y)


tensor([[0.4177, 0.1536],
        [0.6679, 0.3633]])
tensor([[0.9227, 0.4848],
        [0.8525, 0.1784]])
tensor([[1.3405, 0.6385],
        [1.5204, 0.5417]])
tensor([[ 0.5050,  0.3312],
        [ 0.1847, -0.1849]])


In [43]:
x = torch.rand(4,4)
print(x)
y = x.view(-1, 8)
print(y)

tensor([[0.0763, 0.8030, 0.6426, 0.3121],
        [0.4696, 0.6531, 0.3698, 0.9982],
        [0.6094, 0.5812, 0.8902, 0.1351],
        [0.6500, 0.5481, 0.2304, 0.0028]])
tensor([[0.0763, 0.8030, 0.6426, 0.3121, 0.4696, 0.6531, 0.3698, 0.9982],
        [0.6094, 0.5812, 0.8902, 0.1351, 0.6500, 0.5481, 0.2304, 0.0028]])


In [44]:
a = torch.ones(5)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [45]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [51]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")
    print(z)

In [52]:
x = torch.ones(5, requires_grad=True)
print(x)


tensor([1., 1., 1., 1., 1.], requires_grad=True)
