In [22]:
import torch

In [23]:
x = torch.randn(5, requires_grad=True)
print(x)
y = x + 2
print(y)

z = y*y*2 
z = z.mean() #for mean backward 
print(z)


z.backward() #dz/dx
# jacobin matrix with partial derivatives and the we multiply with gradeint vector.
# Its also calle the chain rule 
print(x.grad)
# Sinc our Z is a scaler value we dont have to used agument here for the backward function.

tensor([-1.0328, -1.9608, -0.1143,  0.4928, -0.1418], requires_grad=True)
tensor([0.9672, 0.0392, 1.8857, 2.4928, 1.8582], grad_fn=<AddBackward0>)
tensor(5.6639, grad_fn=<MeanBackward0>)
tensor([0.7737, 0.0314, 1.5086, 1.9942, 1.4866])


In [24]:
#  If Z has more than one value
x = torch.randn(5, requires_grad=True)
print(x)
y = x + 2
print(y)

z = y*y*2
print(z)
v = torch.tensor([0.1, 1.0, 0.001,0.1,0.001], dtype=torch.float32) #
z.backward(v) #dz/dx
print(x.grad)

tensor([ 1.6220,  0.9297,  0.4727,  0.5040, -0.6454], requires_grad=True)
tensor([3.6220, 2.9297, 2.4727, 2.5040, 1.3546], grad_fn=<AddBackward0>)
tensor([26.2384, 17.1668, 12.2280, 12.5402,  3.6700], grad_fn=<MulBackward0>)
tensor([1.4488e+00, 1.1719e+01, 9.8906e-03, 1.0016e+00, 5.4185e-03])


In [25]:
# how to prevent the pytorch to tracking the history and calculating the gredeint FM attribute
# so some times during our training our lopp when we want to update our weights 
# then this operation should not be part of the gradeint computation

x = torch.randn(5, requires_grad=True)
print(x)

#we have three option to do 
# x.requires_grad_(False) #option 1
# x.detach() #option 2
# with torch.no_grad(): #option 3

x.requires_grad_(False)
print(x)

y = x.detach()
print(y)

with torch.no_grad():
    y = x + 2
    print(y)

tensor([-0.0779, -0.3162,  1.4544,  0.9580, -0.7873], requires_grad=True)
tensor([-0.0779, -0.3162,  1.4544,  0.9580, -0.7873])
tensor([-0.0779, -0.3162,  1.4544,  0.9580, -0.7873])
tensor([1.9221, 1.6838, 3.4544, 2.9580, 1.2127])


In [26]:
# Creating Dummy training example 
weights = torch.ones(4, requires_grad = True) #creating weights
for epoch in range(3): 
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)
    # training loop iteration of 1: tensor([3., 3., 3., 3.])
    # training loop iteration of 2: tensor([6., 6., 6., 6.])
    # training loop iteration of 3: tensor([9., 9., 9., 9.])
    # now our weights or our gradeints are clearly incorrect 
    # so before doing the next iteration 
    # We must empyt the gradeint

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [28]:
# Pytorch built in optimizer lets say we have the optimzer from the torch optimization
weights = torch.ones(4, requires_grad = True) #creating weights
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.stop()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor