In [3]:
import torch

In [7]:
x = torch.rand(5, requires_grad=True)
print(x)
y = x + 2
print(y)

z = y*y*2
z = z.mean()

print(z)
z.backward() #dz/dx
print(x.grad)



tensor([0.5989, 0.5052, 0.8556, 0.4582, 0.3045], requires_grad=True)
tensor([2.5989, 2.5052, 2.8556, 2.4582, 2.3045], grad_fn=<AddBackward0>)
tensor(13.0155, grad_fn=<MeanBackward0>)
tensor([2.0791, 2.0042, 2.2845, 1.9666, 1.8436])
