In [3]:
import torch

In [11]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)

z = y*y*2
# z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([3.0129, 0.6973, 1.5229], requires_grad=True)
tensor([5.0129, 2.6973, 3.5229], grad_fn=<AddBackward0>)
tensor([50.2593, 14.5506, 24.8210], grad_fn=<MulBackward0>)
tensor([ 2.0052, 10.7891,  0.0141])


In [12]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()

y = x.detach()
print(y)


tensor([ 1.5973e+00,  1.7829e-01, -9.4118e-04], requires_grad=True)
tensor([ 1.5973e+00,  1.7829e-01, -9.4118e-04])
